title: [Samuel D. McDermott]
description: [The webpage of Samuel D. McDermott
  physicist and machine learning researcher]
logo: self-oct-22.jpg

remote_theme: pages-themes/minimal@v0.2.0
plugins: jekyll-remote-theme